# Index
- key: "/"
  routes:
      - action: "App\\Main\\Controllers\\IndexController"
        method: "index"
        params: ""

# Empty
- key: "[any]"
  routes:
      - action: "App\\Main\\Controllers\\IndexController"
        method: "emptyAction"
        params: ""
